ALTER TABLE ONLY AUT_TUROL ADD CONSTRAINT FK_AUT_TUROL_AUT_TUSER
	FOREIGN KEY (UROL_USER) REFERENCES AUT_TUSER (USER_USER)
;

ALTER TABLE ONLY AUT_TUROL ADD CONSTRAINT FK_AUT_TUROL_AUT_TROL
	FOREIGN KEY (UROL_ROL) REFERENCES AUT_TROL (ROL_ROL)
;