CREATE TABLE AUT_TUSER
(

USER_USER				varchar (50) NOT NULL,
USER_NAME				varchar (10) NOT NULL,
USER_AGE				integer NOT NULL,
USER_POSITION			varchar (10) NOT NULL

)

WITH (
   OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE ONLY AUT_TUSER ADD CONSTRAINT PK_AUT_USER
    PRIMARY KEY (USER_USER)
;

COMMENT ON TABLE AUT_TUSER 
	IS 'Nombre de la tabla'
;

COMMENT ON COLUMN AUT_TUSER.USER_NAME
	IS 'Nombre del usuario'
;

COMMENT ON COLUMN AUT_TUSER.USER_AGE
	IS 'Edad del usuario'
;

COMMENT ON COLUMN AUT_TUSER.USER_POSITION
	IS 'Cargo del usuario'
;