CREATE TABLE AUT_TROL
(

ROL_ROL				varchar (10) NOT NULL,
ROL_DESCRI			varchar (100) NOT NULL

)

WITH (
   OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE ONLY AUT_TROL ADD CONSTRAINT PK_AUT_ROL
    PRIMARY KEY (ROL_ROL)
;

COMMENT ON TABLE AUT_TROL 
	IS 'Nombre de la tabla'
;

COMMENT ON COLUMN AUT_TROL.ROL_ROL
	IS 'ID del rol'
;

COMMENT ON COLUMN AUT_TROL.ROL_DESCRI
	IS 'Descripción del rol'
;